### ISSUE TITLE
Recent change in Godot codebase breaks compilation

### ISSUE THREAD

**Issue by Ranoller** [GodotExplorer/spine#13]
Basically same problem with dragon bones module but in spine_batcher.cpp(89):

https://github.com/sanja-sa/gddragonbones/issues/18

Commit that break compilation:
https://github.com/godotengine/godot/commit/b3e4bc562c07142d48907278f9cc496791ff7b33

**Comment by mjtorn** [comment]
Is it possible to fix this so that it still compiles on 3.0? I had to revert that commit in my fork.

**Comment by Ranoller** [comment]
Is possible to do that commit conditional to version... See same commit in dargonbones module, this module compiles in 3.0 and 3.1

https://github.com/sanja-sa/gddragonbones/commit/24b24aa5ded3e4c8bcef35ffb31ddd5a0277f11c
