### ISSUE TITLE
New changes in Godot breaks Spine module

### ISSUE THREAD

**Issue by K3nIchi** [GodotExplorer/spine#16]
Hi,
I got the lastest version of branch master of Godot and it can´t compile the spine module. Probably because of the lastest changes in Godot:
https://godotengine.org/article/why-we-broke-your-pr

any one found a way to compile the spine module without errors?

**Comment by K3nIchi** [comment]
My coleagues helped me and found a way to compile in the latest version of godot

https://github.com/K3nIchi/spine/tree/spine-fix

**Comment by Geequlim** [comment]
Fixed.

**Comment by K3nIchi** [comment]
Thank you =)
