### ISSUE TITLE
Eventual 3.0 compatibility

### ISSUE THREAD

**Issue by arthurtemple** [GodotExplorer/spine#4]
Hello,

Godot 3.0 is a reality now and some modest efforts would be enough to bring this module up to speed with the stable branch. Newer Godot features, however, open up a lot of possibilities for module developers.

Do you, as project maintainer, have something specific in mind as to what this module should look like alongside Godot 3.0 stable?
Keep on with compatibility updates, GDNative, world domination...

Thanks in advance and congrats for the nice work so far.

**Comment by Geequlim** [comment]
I'll keep fix bugs for this module untill the Official support is released in my spare time.
But there is no plan to port it to GDNative in the near future.
Also no plan to support new version of the spine SDK in the near future.

Thanks for your contribute and hope you enjoy the module ！

**Comment by arthurtemple** [comment]
Fine by me, thanks for your answer.

I'll probably send some PRs your way, feel free to accept or not.
