### ISSUE TITLE
How do you load Spine files?

### ISSUE THREAD

**Issue by danielytics** [GodotExplorer/spine#9]
Sorry if this isn't the right place to ask...

I select load from the menu on the "Resource" key under Spine in the properties inspector and the file browser states that it recognises `.json` and `.skel` files, amongst others, but when I try to load one of the sample exports from Spine (I've tried alien and spineboy, both json and skel files) that I've copied into my Godot project directory, I get an error `Error loading file: Not a resource`. 

The same same steps worked in this video https://www.youtube.com/watch?v=m0liBPf1NW8

What am I missing? Thanks!

**Comment by TheTrope** [comment]
Make sure your exported model is compatible (spine V3.5.51)

**Comment by danielytics** [comment]
I just tried using @thorthur's fork (with Spine 3.6 support) and it gives me the same error. I can't test 3.5.51 as when I downgrade Spine to that version, it fails to load any of the Spine project files I have...

**Comment by TheTrope** [comment]
Don't import the spine projet, use the spine 'import data" and import with Spine (3.5.51) the json you exported before with spine 3.6. Then export it again

**Comment by danielytics** [comment]
That worked! Thank you very much, @TheTrope! I appreciate the help.

I'm not sure why thorthur's 3.6 fork didn't work for me :( but I can use 3.5 for now and maybe the official support will be ready before I want to use newer features.

**Comment by arthurtemple** [comment]
I sometimes encountered the issue (Spine 3.5 and 3.6 alike), yet on `.skel` files only.
Time to test the sample exports then!

**Comment by danielytics** [comment]
Thanks for the response @thorthur, I’ll try a few more `.skel` and `.json` versions and see if I can predictably get it working (or failing). The 3.5 version `.skel` crashed Godot last night (but when I reloaded Godot, it was already loaded and worked perfectly!) and the 3.5 `.json` worked fine (both with your fork), but the 3.6 ones I tried didn’t work (the “not a resource” error). I’ll try it with a few different exports and see what happens.

In any case, I can use the 3.5 `.json` for now so there is no rush to get it fixed.

**Comment by danielytics** [comment]
Now I can't actually reproduce it anymore (using @thorthur's fork), both `.json` and `.skel` work using latest Spine and I tested it with both the standard and pro example exports (I did re-export them myself, though, in case that matters). I really don't know what the problem I was having yesterday was.

**Comment by Geequlim** [comment]
@danielytics The animation for the 3.6 version should be exported with the runtime version `3.6.32`
